### ISSUE TITLE
[BUG] linting fails due to code thinking that both component_style and component_style_rgx are being defined in configuration

### ISSUE THREAD

**Issue by edarsh7** [ia-eknorr/ignition-lint#14]
**Describe the bug**
Using this action workflow with the following configuration in my .github/workflow/lint.yaml file
```
    viewlint:
      name: Lint Ignition Views
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Run JSON linting
          uses: ia-eknorr/ignition-lint@v1.0
          with:
            files: find . -name 'view.json'
            component_style: 'PascalCase'
            parameter_style: 'camelCase'
```
causes the linting to fail with the following error:

![image](https://github.com/ia-eknorr/ignition-lint/assets/34787572/33986ab2-8dfa-4735-8c98-1b542cdfed2b)

**To Reproduce**

1. Configure lint.yaml file
2. commit and push a change to repo
3. check actions tab in github to see that most recent workflow lint fails

**Expected behavior**
running this action workflow should not fail when only either `component_style` or `component_style_rgx` are specified.

**Additional context**
development environment done through WSL on vscode
